services:
  influxdb2:
    image: influxdb:2
    ports:
      - 8086:8086  # Expose InfluxDB on port 8086
    environment:
      DOCKER_INFLUXDB_INIT_MODE: setup
      DOCKER_INFLUXDB_INIT_USERNAME_FILE: /run/secrets/influxdb2-admin-username
      DOCKER_INFLUXDB_INIT_PASSWORD_FILE: /run/secrets/influxdb2-admin-password
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN_FILE: /run/secrets/influxdb2-admin-token
      DOCKER_INFLUXDB_INIT_ORG: UofA  # Organization name
      DOCKER_INFLUXDB_INIT_BUCKET: Muffin  # Bucket name
    secrets:
      - influxdb2-admin-username
      - influxdb2-admin-password
      - influxdb2-admin-token
    volumes:
      - ./InfluxdbDocker/data:/var/lib/influxdb2  # Map local data directory to container's InfluxDB data directory
      - ./InfluxdbDocker/config:/etc/influxdb2  # Map local config directory to container's InfluxDB config directory

  grafana:
    image: grafana/grafana-enterprise:9.5.3  # Use Grafana Enterprise version 9.5.3
    ports:
      - 3000:3000  # Expose Grafana on port 3000
    depends_on:
      - influxdb2  # Ensure InfluxDB starts before Grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin # Grafana default admin username
      - GF_SECURITY_ADMIN_PASSWORD=H3x&9Lmp*V8j # Grafana default admin password
      - GF_SERVER_ROOT_URL=http://localhost:3000  # Grafana root URL
      - GF_SECURITY_ALLOW_EMBEDDING=true  # Allow embedding Grafana dashboards
    volumes:
      - ./grafana_data:/var/lib/grafana  # Persist Grafana data locally
    links:
      - influxdb2  # Link Grafana to InfluxDB container

secrets:
  influxdb2-admin-username:
    file: ./run/secrets/influxdb2-admin-username  # Secret file for InfluxDB admin username
  influxdb2-admin-password:
    file: ./run/secrets/influxdb2-admin-password  # Secret file for InfluxDB admin password
  influxdb2-admin-token:
    file: ./run/secrets/influxdb2-admin-token  # Secret file for InfluxDB admin token

volumes:
  grafana_data:  # Define Grafana data volume
